If a new pinfo() is successfully created but we cannot get its taskstats, it will not have a .ioprio field, so it must be garbage collected. So, initialize .mark to False so that incompletely built objects are garbage collected.
Traceback (most recent call last):
  File "./iotop.py", line 11, in <module>
    main()
  File "/home/g/iotop/iotop/ui.py", line 271, in main
    curses.wrapper(run_iotop, options)
  File "/usr/lib/python2.5/curses/wrapper.py", line 44, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/g/iotop/iotop/ui.py", line 226, in run_iotop
    ui.run()
  File "/home/g/iotop/iotop/ui.py", line 97, in run
    self.process_list.duration)
  File "/home/g/iotop/iotop/ui.py", line 195, in refresh_display
    lines = self.get_data()
  File "/home/g/iotop/iotop/ui.py", line 183, in get_data
    return map(format, processes)
  File "/home/g/iotop/iotop/ui.py", line 167, in format
    line = '%5d %4s %-8s %11s %11s %7s %7s ' % (p.pid, p.ioprio,
AttributeError: 'pinfo' object has no attribute 'ioprio'